### ISSUE TITLE
Publish official docker images

### ISSUE THREAD

**Issue by Trolldemorted** [mit-pdos/noria#182]
I was unable to find official docker images and your readme does not link to any.

Could you publish stable releases on either dockerhub or ghcr?

**Comment by jonhoo** [comment]
Given that I was working on this as a research project for my PhD (which is [now done](https://jon.thesquareplanet.com/papers/phd-thesis.pdf) :tada:), that probably won't happen. Especially because Noria as it exists in this repository isn't really something you should be running "for real". It's a research prototype, that would require significant engineering to get to a production-ready state :)

**Comment by Trolldemorted** [comment]
Oh you underestimate our love for obscure database solutions when we build security CTF challenges 😛

I see noria has trouble building, do you still have a Cargo.lock file?

**Comment by jonhoo** [comment]
Ooooh, nice!

I bet you're running into https://github.com/mit-pdos/noria/issues/181 — try pinning the version of `evmap` like I suggested there and see if that works?
